language: python
python: "3.3"
# command to install dependencies
virtualenv:
 system_site_packages: true
before_install:
 - sudo apt-get install libgmp-dev
 - sudo apt-get install python3-crypto
install: 
 - pip install -r requirements.txt
# command to run tests
script:
 - cd p2p
 - python -m unittest -v
